set(XRAY_DIRECTX_SDK_ROOT "" CACHE PATH "Legacy DirectX SDK root for Direct3D, DirectInput, DirectPlay, D3DX, and dxguid libraries")
set(XRAY_OPENAL_ROOT "" CACHE PATH "Legacy OpenAL SDK root")
set(XRAY_EAX_ROOT "" CACHE PATH "Legacy EAX SDK root")
set(XRAY_XIPH_ROOT "" CACHE PATH "Legacy Ogg/Vorbis/Theora dependency root")
set(XRAY_LUA_ROOT "" CACHE PATH "Historical Lua dependency root, if not using the checked-in xrLUA sources")
set(XRAY_LUAJIT_ROOT "" CACHE PATH "Historical LuaJIT dependency root, if required")
set(XRAY_LUABIND_ROOT "" CACHE PATH "Legacy luabind dependency root")
set(XRAY_BOOST_ROOT "" CACHE PATH "Legacy Boost root compatible with the selected luabind version")
set(XRAY_LOKI_ROOT "" CACHE PATH "Legacy Loki include root")
set(XRAY_MAGICFM_ROOT "" CACHE PATH "Optional MagicFM SDK root used by old AI/tool projects")
set(XRAY_3DSMAX_SDK_ROOT "" CACHE PATH "Optional 3ds Max SDK root for DCC plugins")
set(XRAY_MAYA_SDK_ROOT "" CACHE PATH "Optional Maya SDK root for DCC plugins")
set(XRAY_LIGHTWAVE_SDK_ROOT "" CACHE PATH "Optional LightWave SDK root for DCC plugins")

function(xray_report_dependency name value)
  if(value)
    message(STATUS "${name}: ${value}")
  else()
    message(STATUS "${name}: <not set>")
  endif()
endfunction()

xray_report_dependency("XRAY_DIRECTX_SDK_ROOT" "${XRAY_DIRECTX_SDK_ROOT}")
xray_report_dependency("XRAY_OPENAL_ROOT" "${XRAY_OPENAL_ROOT}")
xray_report_dependency("XRAY_EAX_ROOT" "${XRAY_EAX_ROOT}")
xray_report_dependency("XRAY_XIPH_ROOT" "${XRAY_XIPH_ROOT}")
xray_report_dependency("XRAY_LUA_ROOT" "${XRAY_LUA_ROOT}")
xray_report_dependency("XRAY_LUAJIT_ROOT" "${XRAY_LUAJIT_ROOT}")
xray_report_dependency("XRAY_LUABIND_ROOT" "${XRAY_LUABIND_ROOT}")
xray_report_dependency("XRAY_BOOST_ROOT" "${XRAY_BOOST_ROOT}")
xray_report_dependency("XRAY_LOKI_ROOT" "${XRAY_LOKI_ROOT}")
xray_report_dependency("XRAY_MAGICFM_ROOT" "${XRAY_MAGICFM_ROOT}")
xray_report_dependency("XRAY_3DSMAX_SDK_ROOT" "${XRAY_3DSMAX_SDK_ROOT}")
xray_report_dependency("XRAY_MAYA_SDK_ROOT" "${XRAY_MAYA_SDK_ROOT}")
xray_report_dependency("XRAY_LIGHTWAVE_SDK_ROOT" "${XRAY_LIGHTWAVE_SDK_ROOT}")
